### ISSUE TITLE
Model & Response model들 리팩토링

### ISSUE THREAD

**Issue by enebin** [Nexters/Naenio-iOS#108]
@Choyoonyoung98 님 안녕하세요. 데이터 모델 쪽 리팩토링 관련 제안 사항이 있어 멘션 드립니다.

## 문제점
현재 Model들이 너무 산발적으로 존재하는 것 같습니다. 제가인식한 문제는 다음과 같은데

다음 Post.swift파일의 모습입니다.([링크](https://github.com/Nexters/Naenio-iOS/blob/main/Naenio/Sources/Home/Models/Posts/Post.swift))
``` Swift
// Post.swift
struct Post: ModelType, Identifiable, Equatable {
    static func == (lhs: Post, rhs: Post) -> Bool {
        return lhs.id == rhs.id
    }
    
    let id: Int
    let author: Author
    var voteCount: Int
    let title: String
    let content: String
    var choices: [Choice]
    var commentCount: Int
}

struct Choice: ModelType {
    let id: Int
    let sequence: Int
    let name: String
    var isVoted: Bool
    var voteCount: Int
}
```

`Post`가 존재하고 `Choice`가 Post.swift파일 안에 **전역적**으로 선언되어있습니다.

다음은 PostResponseModel.swift입니다. 
``` Swift
//  PostResponseModel.swift
struct PostResponseModel: ModelType {
    static func == (lhs: PostResponseModel, rhs: PostResponseModel) -> Bool {
        return lhs.id == rhs.id
    }
    
    let id: Int
    let memberId: Int
    let title: String
    let content: String?
    var choices: [PostResponseModel.Choice]
    var createdDateTime: String
    var lastModifiedDateTime: String
    
    struct Choice: ModelType {
        let id: Int
        let sequence: Int
        let name: String
    }
}

```
`Choice`가 내부에 또 선언되어있습니다. 

CommentModel.swift도 마찬가지입니다. 얘는 내부에 `Author`를 또 새로 가지고 있습니다. `Author`는 피드 쪽 모델에서 전역적으로 들고 있는 것으로 알고 있습니다.
``` Swift
struct CommentModel: ModelType {
    let totalCommentCount: Int
    let comments: [Comment]
    
    struct Comment: ModelType {
        let id: Int
        let author: Author
        let content: String
        let createdDatetime: String
        let likeCount: Int
        let isLiked: Bool
        let repliesCount: Int
        
        struct Author: ModelType {
            let id: Int
            let nickname: String?
            let profileImageIndex: Int?
        }
    }
}
```

- 그냥 쓸 수도 있긴 합니다만,, 함수에서 파라미터로 넘길 때 가끔 타입 추론을 잘못해서 에러가 나는 문제가 발생했습니다.

## 원인을 파악해봄
- 리스폰스로 오는 자료형들이 다 미묘하게 다르더군요. 어떤 건 프로퍼티가 일부만 오고 어떤 건 전부 다 오고.
- 그러다보니 아예 `struct`를 새로 만드는 식으로 막게 된 것 같습니다.
- 이와 별개로 여기 저기에 model들이 너무 흩어져 있어 뭐가 어디에 있는지 어떻게 관리되고 있는지 파악하기가 다소 힘들어진 것 같습니다.

## 해결책?
- `struct` 디코딩 시  없는 키값이 있는 건 에런데 있는 키값에 밸류가 없는 건 에러가 아닌 걸로 알고 있습니다. 
- 그러므로 저런 식으로 중첨되어 선언된 `struct`들은 전역적으로 선언된 걸 재사용하는게  좋지 않을까 하는 의견입니다.
- 리스폰스 모델의 경우 원하는 `struct`를 만드는 데 빈 내용이 있으면 문제가 생길 수 있겠죠?? 지금도 어떻게 잘 막으신 것 같긴 한데 https://github.com/Nexters/Naenio-iOS/pull/83#discussion_r954412239 여기서 언급한 방법으로 리팩토링하면 어떨까용??
- 모델들을 한 눈에 볼 수 없어 생길 수도 있는 문제라고 생각하는데요. 따라서 현재 폴더별로 선언된 model들을 model이라는 새로운 공통의 폴더로 다 옮기는 것은 어떨까 싶습니다.

## 해결책 기반 리팩토링 작업 정리
- 중복 선언된 모델들 골라내서 삭제 & 병합하기
- 리스폰스 모델 -> 데이터 모델로 바꾸는 메소드 `extension`에 구현하기(https://github.com/Nexters/Naenio-iOS/pull/83#discussion_r954412239)
- model 폴더 생성 후 모든 모델들 다 몰아넣기

**Comment by enebin** [comment]
검토해보시고 편하게 리뷰 주십셔ㅎㅎ

**Comment by Choyoonyoung98** [comment]
> 해결책?
struct 디코딩 시 없는 키값이 있는 건 에런데 있는 키값에 밸류가 없는 건 에러가 아닌 걸로 알고 있습니다.
그러므로 저런 식으로 중첨되어 선언된 struct들은 전역적으로 선언된 걸 재사용하는게 좋지 않을까 하는 의견입니다.

요 내용은 사용되지 않을 수도 있는 키값에 대해서는 Optional 처리하면 에러가 발생안된다는 말씀이신가요??

저도 함수에서 파라미터로 넘길 때 가끔 타입 추론을 잘못해서 에러가 나는 문제가 발생했어서,, 문제 인식하던 참이었습니다 ㅜ
아래 내용으로 진행하는 리팩토링은 우선 좋습니다~!

### TODO
- [ ] 리스폰스 모델 -> 데이터 모델로 바꾸는 메소드 extension에 구현하기(https://github.com/Nexters/Naenio-iOS/pull/83#discussion_r954412239)
- [ ] model 폴더 생성 후 모든 모델들 다 몰아넣기

**Comment by enebin** [comment]
확인 감사합니다!!

> 리스폰스 모델 -> 데이터 모델로 바꾸는 메소드 extension에 구현하기
얘는 편한대로 해주시면 될 것 같고

> model 폴더 생성 후 모든 모델들 다 몰아넣기 
얘는 conflict 심하게 날 것 같아서 나중에 서로 시간 안 겹칠 때 하거나 작업 다 마무리하고 해도 좋을 것 같습니다?

**Comment by Choyoonyoung98** [comment]
> model 폴더 생성 후 모든 모델들 다 몰아넣기

네 api 다 붙이고 merge 필요한 PR 없는 시점에 호딱 진행하면 될 것 같습니다
