### ISSUE TITLE
NaenioAPI 관련 건의사항

### ISSUE THREAD

**Issue by enebin** [Nexters/Naenio-iOS#24]
## 목표
NaenioAPI 테스트 코드 작성 중 몇 가지 제안 및 의문이 생겨 이슈 납깁니다.

### 1
https://github.com/Nexters/Naenio-iOS/blob/7f94fdd9355e4b09fb240b9062453bd719cacfc2/Naenio/Utils/Network/API/NaenioAPI%2BWrapper.swift#L14
https://github.com/Nexters/Naenio-iOS/blob/7f94fdd9355e4b09fb240b9062453bd719cacfc2/Naenio/Utils/Network/API/NaenioAPI%2BWrapper.swift#L25
- 위에서 Wrapper라는 명칭이 중복되어 사용돼서 헷갈리는 감이 있습니다. 둘 중 하나의 이름이 바뀌면 어떨지 제안 드립니다.
- 그런데 하나 궁금한 것이, `wrapper`는 `MoyaProvider`에 제공하려고 만드신 것으로 추측했습니다. 그런데 `MoyaProvider<NaenioAPI>`같이 wrapper없이 제공해도 동작하는 것 같은데 혹시 제가 놓친 부분이 있을까요? 확인 부탁드리겠습니다!

### 2
https://github.com/Nexters/Naenio-iOS/blob/7f94fdd9355e4b09fb240b9062453bd719cacfc2/Naenio/Utils/Network/API/NaenioAPI.swift#L27
- 현재 `NaenioAPI`의 `sampleData`부분이 비어있는 것 같습니다. Test 작성을 위해서는 이 부분이 채워져야 하는데 만약 여유 생기신다면 부탁 좀 드리겠습니다!
- 지금은 제가 필요한 것만 몇개 채워서 쓰고 있습니다. 제가 쓴 mock data는 따로 push하지 않겠습니다!(해도 되나?)
- ex. 
``` Swift
var sampleData: Data {
    switch self {
    case .login(_):
        return "{\"token\": \"mock-apple-token\"}".data(using: String.Encoding.utf8)!
    default:
        return "".data(using: String.Encoding.utf8)!
    }
}
```

**Comment by Choyoonyoung98** [comment]
### 1. 
맞습니다. `MoyaProvider<NaenioAPI>`와 같이 작성해도 동작에는 문제가 없습니다! 코드 가시성을 위해 wrapper로 선언해두었는데, 삭제하고 말씀하신 것과 같이 사용해도 무관할 것 같습니다.

### 2.
sampleData는 API 붙이는 족족 추가해서 각자 push하면 될 것 같습니다 :) 
다만 요거도 조금 길어질 것 같아서 `NaenioAPI+MockData`와 같이 따로 빼고, dataEncoded extension 만들어서 사용하는 게 좋을 것 같습니다.

```
extension String {
   var dataEncoded: Data {
      return self.data(using: String.Encoding.utf8)!
   }
}
```
