### ISSUE TITLE
PR 보실 때 주의사항

### ISSUE THREAD

**Issue by enebin** [Nexters/Naenio-iOS#32]
@Choyoonyoung98 님, PR 보실 때
#31(얘는 아직 덜 됨. 네비게이션은 맞춰놨음)  -> #30 -> #29 -> #27 순서로 봐주십셔. 다 base 브랜치가 달라서.

그리고 
#24 이것도 수정 부탁드립니다.

나중에 얘기해야 할 것 같은데 카드 뷰 게시글 조회 API쪽도 연동 부탁드려요. 이건 아직 서버도 안나온 것 같아서 시간 나실때 해주시면 될듯요!!

화이팅입니다 🔥🔥🔥

**Comment by Choyoonyoung98** [comment]
- [x] PR review
- [ ]  #24 수정
- [ ] 게시글 조회 API 연동
